/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jaitl.dynamodb.mapper

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
