name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew lib:build
      - name: Prepare to publish
        run: |
          echo '${{secrets.GPG_KEY_CONTENTS}}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" \
          --output secret.gpg publish_key.gpg
      - name: Publish
        run: >
          ./gradlew lib:publish
          -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secret.gpg
          -Psigning.keyId=${{secrets.SIGNING_KEYID}}
          -Psigning.password='${{secrets.SIGNING_PASSWORD}}'
          -PsonatypeUsername=${{secrets.SONATYPE_USERNAME}}
          -PsonatypePassword='${{secrets.SONATYPE_PASSWORD}}'
          -PreleaseVersion=${GITHUB_REF:11}